name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CUnit
      run: sudo apt-get install libcunit1 libcunit1-dev

    - name: Build
      run: make all

    - name: Run Tests
      run: make test
